name: Docker Image CI

on:
  push:
    branches: [ "main" ] # hoặc master, tùy repo 
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push notification-service
        uses: docker/build-push-action@v5
        with:
          context: notification-service/NotificationService/   # thư mục gốc chứa code
          file: notification-service/NotificationService/Dockerfile  # đường dẫn Dockerfile
          push: true
          tags: quanghau123/notification-service:latest

      - name: Build & Push smarttasty-service
        uses: docker/build-push-action@v5
        with:
          context: smarttasty-service/backend/
          file: smarttasty-service/backend/Dockerfile 
          push: true
          tags: quanghau123/smarttasty-service:latest

      - name: Build & Push socket-server
        uses: docker/build-push-action@v5
        with:
          context: socket-server/WebSocketServer/
          file: socket-server/WebSocketServer/Dockerfile
          push: true
          tags: quanghau123/socket-server:latest

      - name: Build & Push chatbot-service
        uses: docker/build-push-action@v5
        with:
          context: chatbot-service/ChatbotService/
          file: chatbot-service/ChatbotService/Dockerfile
          push: true
          tags: quanghau123/chatbot-service:latest

